### ISSUE TITLE
Nested filters

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#1]
Filters were originally intended to have more than one level, e.g.: 

-> anaesthesia
->->GABAergic
->->-> propofol
->->-> ...
->-> Volatile Ethers
->->-> isoflurane
...

It should be possible to select any of the categories to indicate all from the category, as well as selecting individual sub points.

This tree can in principle be arbitrarily deep. I see no reason to fix a maximum depth beyond the limits of what fits on a screen.

**Comment by tgetgood** [comment]
@hlesaint Using issues like this lets us track each of your feedback points separately and have a conversation around each.

**Comment by hlesaint** [comment]
Ok, that's great. Then let's go with nested filters then as originally intended.

**Comment by tgetgood** [comment]
This has been implemented. The design could use some work, but the functionality is there both in the UI and the database to store trees of tags. 

Redesign can be its own issue in the future.
