### ISSUE TITLE
Extract creation site: option for back to extract list

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#14]
Once we are in the extract creation site we cannot go back to the extract list without creating an extract. Would be great to have another "go back" option in the menu below welcome user.

**Comment by tgetgood** [comment]
Right now you can click on the name "openmind" to go back to the front page. That's not obvious at all, but it's a convention on many sites. 

#13 will also make it so the browser back button works properly and takes you back to where you were.

In addition typing a new search in the search bar is supposed to bring you to a search, but I seem to have broken that. 

I think these three mechanisms will suffice. What are your thoughts?

**Comment by hlesaint** [comment]
Ah, I see. That's sound. Basically more than sufficient. Intuitively I thought I go back where I came from, so maybe this option wouldn't harm, but it's apparently not necessary.

**Comment by tgetgood** [comment]
It wouldn't be a problem to put a "back" or "cancel" button to the left of the "create" button. That's a common approach as well.  

It doesn't hurt to be too clear.

**Comment by tgetgood** [comment]
@hlesaint I've added the 3 ways to navigate back that I originally mentioned. Try it out and let me know if you think it needs the fourth.

**Comment by hlesaint** [comment]
Since I got used to click on "openmind" I would say no need to to implement the fourth way, at least not for me. Although it would't harm, it is certainly not a priority point.
