### ISSUE TITLE
Comment discussion trees

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#15]
When hovering over the "comments" link in an extract we need to show a window with the most recent comments right in the search window.

Additionally, when you click on the comments link, it should take you to a page that shows you the extract and the entire dialog surrounding it. I'm thinking of stealing heavily from reddit for this page; there's no need to reinvent it. 

As part of this, comments need to have explicit authors, referrents, publication dates, histories, and be organised into conversation threads. All of this should be reflected in the comment page, and some of it in the hover window.

Note also that a big part of the comment page is to allow people to chime in, it's not read only.

**Comment by hlesaint** [comment]
Perfect! Does this include rating of comments? – most relevant occur on top?

**Comment by tgetgood** [comment]
It should, yes.

**Comment by tgetgood** [comment]
We have a very basic display working for now. 

I'm demoting full discussion trees to beta priority.
