### ISSUE TITLE
History display

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#20]
Hovering over the "history" link of an extract should show a summary of the history metadata if there is any.

If the history becomes involved then we will also need a dedicated page for history of an extract.

**Comment by hlesaint** [comment]
Agree on that. I ask myself if it would make sense to get the thumbnails /shortlist /etc displayed by hovering over it, but the full list by clicking on it without entering a new page. Not sure about that – just a thought.

**Comment by tgetgood** [comment]
We can try that and see how it works. I suspect that if there's a lot of history then scrolling the mini view might get awkward. The only want to find out though is to give it a shot.

**Comment by tgetgood** [comment]
This was completed as part of #55.

**Comment by hlesaint** [comment]
What do you think about moving the history option to the details section. It is important, but not really interesting on the fly and we have less complexity /more space on the extract. #54

**Comment by tgetgood** [comment]
This is sensible. I'll make a new issue for it.
