### ISSUE TITLE
Related material display

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#21]
When hovering over the "related" link of an extract, we should show a summary of the material that has been marked as related to this extract both by the author and by the community at large.

**Comment by hlesaint** [comment]
![C773CB12-6B10-4754-A90B-62A563A07143](https://user-images.githubusercontent.com/44240982/64697623-86543700-d4a1-11e9-87cc-55398ade089b.jpeg)

**Comment by hlesaint** [comment]
Yes, and it would be great to access the related extracts from there. Is it possible to display related extracts from there? What do you think about an option to list originals by click like in the above picture?

**Comment by tgetgood** [comment]
That could work. We could also have nested hovers as in a menu. We might want to add new categories in the future such as "confirms" or "reproduces", etc. so we want something like this that we can extend.

**Comment by hlesaint** [comment]
Here again, the question is if we only want to display extracts or to list papers and their respective extracts (see https://github.com/hlesaint/openmind/issues/26). 

If we decide for only extracts like in the above illustration than we need to think about a way how to best relate to them.

**Comment by hlesaint** [comment]
https://github.com/hlesaint/openmind/issues/26#issuecomment-531401046_

**Comment by hlesaint** [comment]
Ok, I think we can close this issue:
– display of related extracts is based on a list when mouse over /click on "related to" /"confirmed by" or "in contrast to" #43
– extracts are related on create /modify extract page #44  
– we only relate to and list extracts (no external sources)

**Comment by hlesaint** [comment]
– we can cover all possible relations with these 3 categories: "related to" (neutral) /"confirmed by" (+) and "in contrast to" (-)
– I take this to #43
