### ISSUE TITLE
Figure display

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#23]
When hovering over the figure link of an extract, thumbnails of all uploaded figures should be displayed.

Clicking on the link should bring you to a page showing the full sized figures.

Should each figure have it's own page? Probably. And with left and right buttons and maybe a thumbnail slider as in many photo browsing applications.

**Comment by hlesaint** [comment]
Interesting idea. You mean if an extract has more than one figure or actually sliding between images of the previous and next extract? 

For normal extracts I would say: one extract, one figure. For review extracts we could display to the figures of the referenced originals – but this is something for after beta.  

Does it help if hovering shows the thumbnail and clicking on it enlarges the figure, still within the list? The figure may appear in a white frame which can also contain a figure caption to guide the readers eye?

**Comment by tgetgood** [comment]
One figure per extract simplifies things a lot. Let's keep it simple then and try to force people to be concise. 

As for the full size image, we'll try a few options. The fastest will be a new page for the full size image, so I'll start with that and we can try variations from there.

**Comment by hlesaint** [comment]
Looking forward to!
