### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#24]
When creating or editing an extract, we need to add code that checks that the data entered is sane. I.e. uploaded figures are really images, urls are valid, extract text is not empty, etc..

This needs to be implemented both in the client (browser) so as to give feedback on what is wrong, and on the server to prevent corrupt data making it into the database.

**Comment by hlesaint** [comment]
That's certainly a good thing to do.

**Comment by tgetgood** [comment]
This is working for the fields we have right now, and should be easy enough to extend as we refine the rest of the form.
