### ISSUE TITLE
Grab details of linked papers automatically from pubmed

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#26]
We need at least the author, journal, publication date, title, and abstract. 

Should also create unique ids so that we can search extracts which refer to a given paper in any capacity.

**Comment by hlesaint** [comment]
You mean if an extract refers on another extract /paper?

**Comment by hlesaint** [comment]
Would be an interesting idea. Fully agree with the first part.

**Comment by tgetgood** [comment]
This refers to the extract creation. If you enter "https://www.ncbi.nlm.nih.gov/pubmed/22209807" as the source article, then we should be able to go to the link and show the reference of the extract as "Nasrallah FA, Tan J, Chuang KH (2011)" and display the abstract on hover. 

The same goes for related material. We want authors to enter links to papers, but we want to refer to papers in the more traditional citation style. 

We should add support for other DOIs as well, but pubmed is probably enough for the very beginning.

**Comment by hlesaint** [comment]
For the general usage (creating an extract) I find the process very clear. It gets difficult in the case of related material: do we want to refer now to entire papers or rather to other extracts? In the original openmind presentation you have first a list of papers and if you click on the arrow or triangle next to it you get a list of extracts that originate from the respective paper (I didn‘t illustrated this in my latest example, but it is worth to consider an option).

Indeed, it is more specific to refer on extracts than on a paper. It's easier to find them in openmind and the context what exactly is referred to is clearer. Papers on the other hand would give the option to refer to something outside the databank, but it would't be clear what exactly is referred to. 

Another question is: how we select the extracts? When we only enter the pubmed url, every extract that originated from that paper could be selected. But maybe a particular extract has nothing to do with it? This extract could then be manually deselected. 

This decision appears somewhat complicated, but in the long run it would be instrumental to visualize and navigate through extracts by means of related to /confirmed by /in contrast to. I kind of like the idea (including a visual representation at a later stage), but then we need to have a clear structure there. 

What do you think?

**Comment by tgetgood** [comment]
I was thinking that related material can be either an extract or a paper. If it's a paper, then the pubmed link should uniquely identify it. 

But I think you have a point that requiring related material to be extracts will make the relation more specific. We can always depend on the fact that extracts are sourced from papers to connect papers with each other at a higher level. 

You're right that to enter related extracts is more complicated since you need some way to search and find the right one. That interaction needs to be thought out more.

**Comment by tgetgood** [comment]
This is done for the source article. I'm closing because we're going to link to extracts in related material, so pubmed won't be necessary.
