### ISSUE TITLE
Create (or find) a favicon

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#28]
A favicon is the little icon that is displayed in the left side of the browser tab before the page name. 

Any ideas for an icon should go here.

**Comment by hlesaint** [comment]
very good point. I'll think about it.

**Comment by hlesaint** [comment]
![E842F7B7-E977-4933-8726-8708E0D07AAD](https://user-images.githubusercontent.com/44240982/64926567-2a6e1300-d7ff-11e9-9eb9-dcd08ac795a3.png)

**Comment by hlesaint** [comment]
The owl on the right was the first thing I came up with. Although it's kind of fun, it doesn't match the overall style of our platform. A better alternative is a play of words: OpenMind is abbreviated OM, which has an established symbol. I think the simple white in blue (upper right) would make a good favicon.

**Comment by hlesaint** [comment]
What do you think?

**Comment by hlesaint** [comment]
It appears somewhat difficult to find a good symbol for anesthesia..

**Comment by hlesaint** [comment]
ॐ
<img width="50" alt="OM" src="https://user-images.githubusercontent.com/44240982/82753750-61ea8180-9dc8-11ea-8982-8438c0c7f26f.png">

**Comment by hlesaint** [comment]
I'm not a graphic designer, but this could be a start. It's a very liberal variation of the OM symbol. It looks a bit Hawaiian, and it happened to have some kind of symbolism: the full white circle may be seen as a representation of consciousness itself. Our scientific methods for studying consciousness are limited to superficially examining its expression in different species, modalities, scales and brain states "from the outside" (represented by empty circles), which partially overlap at the outer border of consciousness. And yet these phenomena are separate from the real thing that produces them, but do not allow it to be examined itself (the "hard problem").

At the same time, it can be seen as an eye: "consciousness" is derived etymologically from _con sciencia_ (lat. with-knowledge) and thus from conscience. The idea of an intrinsic self-observation by another (God) is in fact the earliest concept of consciousness in the West. 

It's a first draft, maybe we can build up on it.

<img width="666" alt="OM favicon" src="https://user-images.githubusercontent.com/44240982/82835253-c9d1c280-9ec3-11ea-9779-1e91affd298a.png">

**Comment by tgetgood** [comment]
These are a great start. I'll try a few and see which looks best. I particularly like the top row middle and second row far right.

**Comment by hlesaint** [comment]
Perfect, some variations of these two. PDF contains vector graphics with all versions.

<img width="645" alt="Bildschirmfoto 2020-05-27 um 17 55 16" src="https://user-images.githubusercontent.com/44240982/83043772-9158f280-a043-11ea-9756-66e77aabf79e.png">

[logo_favicon.pdf](https://github.com/openmindanesth/openmind/files/4689964/logo_favicon.pdf)

**Comment by tgetgood** [comment]
I've added the second row, second from the left as a test. I like the top row second more, but a favicon needs to be shrunk down to 32x32pixels, so all fine detail gets lost.

**Comment by tgetgood** [comment]
I think the favicon we have works pretty well. I'm closing this for now, it can be reopened if we think of a better one down the road.
