### ISSUE TITLE
Creating an extract with "confirmed by" references fails

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#30]
Something is funny with the elastic schema. Need to get to the bottom of that.

**Comment by tgetgood** [comment]
Same goes for contrast and related.  Comments are fine though...

**Comment by hlesaint** [comment]
I don't get the comments displayed in FF and GC at my old operation system (need a new one to evaluate). Yet, mobile version OSx doesn't display comments either (also difficult to hover here… better click?).

**Comment by tgetgood** [comment]
Comments get saved to the database, but there's no display for them yet. That will come with #15

**Comment by tgetgood** [comment]
Solved as part of the schema update for extract editing.
