### ISSUE TITLE
Priority list

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#33]
Since time is limited and our plan ambitious, I thought about a list of things, which could be helpful to treat with priority starting with the extract creation. If we want to soon recruit students who create extracts, the following points could support /enable their mission:

~– drag & drop figures (and store them)~
~– display figures (in some way)~
~– possibility to write (and display) figure captions~
~– display author, year, abstract (grab details from pubmed)~
~– store & display comments (in some way)~
~– "modify extract" option~
~– select 1 of 2 extract categories (original extract /lab report)~
~– display /label extract category (like in presentation) and make it searchable!~
– possibility to manually type in author, year, abstract (for lab reports)

I think these are the most important steps to ensure a successful preliminary extract creation. They should give fundamental integrity to avoid going through all extracts after adding new options. 

What do you think?

**Comment by tgetgood** [comment]
I think this is a good list to focus on. It largely overlaps with issues that are already here; I'll go through and add what isn't.

**Comment by hlesaint** [comment]
Great, thanks very much!

**Comment by tgetgood** [comment]
#35 is the only outstanding issue in this list, so I'm going to close this one.
