### ISSUE TITLE
Detailed source article entry

### ISSUE THREAD

**Issue by tgetgood** [openmindanesth/openmind#35]
Ideally, authors will enter a link to the source paper, but if that's not possible, then we should have a fallback where they enter the citation. 

It would be good to have them enter the abstract as well, but there are copyright issues with that.

**Comment by tgetgood** [comment]
We need detailed entry options for both article extracts and lab note sourcing now. 

For lab notes, the fields that seem important are: investigator (should it default to "me", as retrieved from Orcid?), lab name (if relevant), institution, date of observation (distinct from date of extract creation).

**Comment by hlesaint** [comment]
**published article** 
check box: peer-reviewed. Using pubmed listed /non-pubmed listed instead, the check-box could lead to the appearance of a detailed source article entry (#56):
Title, author(s), Year, Journal, ID (if existent), abstract – all separate input windows

**lab notes** 
Fully agree with the above suggestions (I like the idea of "me" as default), separate input windows #49
