### ISSUE TITLE
source materials (instead of details)

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#42]
Source materials can be links to open repositories to store original data, code, etc. which is related to the article or lab note.

"source" can replace "details" on the extract sheet; information related to "details" can go in "comments".

**Comment by hlesaint** [comment]
<img width="687" alt="source" src="https://user-images.githubusercontent.com/44240982/82759110-65dbcb00-9deb-11ea-9a71-29922b61f863.png">

**Comment by tgetgood** [comment]
Will the word "source" be confused with the reference article? "data" might be better, though data is such a vague notion. What about "reproducibility"?

**Comment by hlesaint** [comment]
I felt similar about that. I see the point for "reproducibility". Yet, as it is the goal (or wider context), not the thing you can expect from clicking it, I'd tend to "data" for now in lack for a better word. (Fun fact: It might help that it coincidentally gets further context from the term before, which together read "related" "data".) Maybe we'll come up with something more suitable later.

**Comment by hlesaint** [comment]
What do you think about "resources"? There could be also more links to resources than only one. Then we could give the chance to add multiple resources in the extract creation /edit page by clicking the [+]:

<img width="1094" alt="Bildschirmfoto 2020-07-09 um 21 51 14" src="https://user-images.githubusercontent.com/44240982/87084339-5a732080-c22e-11ea-84df-7ed818cfc404.png">

which could be displayed like that in the extract search page:

<img width="1143" alt="Bildschirmfoto 2020-07-09 um 21 46 05" src="https://user-images.githubusercontent.com/44240982/87084039-dc167e80-c22d-11ea-9287-49382adca080.png">

**Comment by tgetgood** [comment]
I like the description element. it's hard to know what a link is without clicking on it. 

Do you think there would often be more than one resource for a single extract? I guess I'm asking: is this a place to try and push people to narrow down the scope of the extract? As we do with a single figure and a word limit.

**Comment by hlesaint** [comment]
I see the point. Maybe restricting to one link helps to limit the amount of linked data to one repository and thus focus on one key message. There are other ways to provide links to code and toolboxes as you can write your "abstract /description" for lab notes yourself. We could encourage people to do so in the text field for the description.

**Comment by tgetgood** [comment]
Thinking about this more, it seems pretty likely that someone could have separate links to both their code and their data. We would certainly want both.

**Comment by tgetgood** [comment]
I've allowed this to take multiple resources as in the mockups. If we decide later that there should only be one, it's a simple enough change to make.

**Comment by hlesaint** [comment]
It's great we have the resources now on the extract search page! I also like that solution on the creation page. 

One comment on the scaling of the input fields: right now it seems the size is hard coded in pixels, which cuts off the term "toolboxes".
<img width="461" alt="Bildschirmfoto 2020-07-19 um 15 02 15" src="https://user-images.githubusercontent.com/44240982/87875325-e0326100-c9d0-11ea-82cd-d2b04010b43c.png">
Would it be an option to scale it in percentage to the absolute page size? What do you think?

**Comment by hlesaint** [comment]
What do you think about calling it "repo" or "repos" instead of "resources"? That's short and catchy and it is where the links lead to: repositories of data, code, toolboxes.

**Comment by tgetgood** [comment]
I don't have a preference between 'repos' and 'resources', I think they both capture the ideal well. Let's try repos, and see how it looks in comparison. 

As for the creation boxes, I'll make them take the whole width of the page, that's simple enough.
