### ISSUE TITLE
"related to" option: extract creation page

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#44]
Extract creation page: the foundation for our later network view requires a simple way to tag other extracts with either "related to (neutral)", "confirmed by (+)", or in "contrast to (-)". 

You may have an input box to type search terms in. Based on your input a list of extracts appears. The more specific your search terms, the more specific (and narrow) the list of extracts. You can drag and drop specific extracts from that list to one of the 3 categories on the left: "related to", "confirmed by", or in "contrast to".

<img width="691" alt="related to" src="https://user-images.githubusercontent.com/44240982/82757649-1ba21c00-9de2-11ea-9283-006f3d955f92.png">

The number behind the category refers to the number of extracts in that category. When you click on one of the categories a list opens that shows all extracts in that category. You can remove extracts or put them into other categories by drag and drop. When you click to the search field above the list it shows again the extracts that suits the search term.

Further specification may be provided by using the filter tags below. 

Note that only the most important info is displayed on the extracts here: metadata (colored circle), comments, related, tags, figure, and author et al. (year). The other options are not relevant for that step.

To motivate contributors to relate their freshly created extract to others, the search field could at first automatically mirror the extract text. The list is then initially created based on that.

**Comment by hlesaint** [comment]
I really like the implementation, it's simple and straight-forward. Few bugs I found (with Firefox):

– you can relate the same extract multiple times.
– once you relate an extract there is an x, but you cannot delete the extract. 

– you can relate the extract to itself (appears in the list). 
– when you did that and save it, edit the extract again, and you relate the same extract again: 
..... – the save button doesn't close the extract creation page anymore
..... – when you cancel there is a copy of the extract on the extract search page 

– if you edit the copy the input window ("what have you discovered") is sometimes empty (not always)

**Comment by hlesaint** [comment]
Just figured out all the above comments are only true for edit option. When you create an extract these functions work just fine (Firefox):
✓ – each extract can be related only once per category (neutral, +, -). 
✓ – extracts can be deleted from list by crossing out
– relating extract to itself is not an issue when creating a new extract, because you do not specify your extract in the beginning, so we cannot prevent people from doing that (which is ok). When editing an extract this should ideally not be possible.

**Comment by hlesaint** [comment]
It might help if there is a visual clue, which shows that you actually related an extract. As the list continues below the screen you don't know whether an extract was related or not (so you have to scroll down to be sure). An idea would to change color of the respective category on the extract you clicked to "related to", "confirmed by", "in contrast to", e.g., from grey to blue, so you know directly.

**Comment by tgetgood** [comment]
Editing still isn't quite finished. 

One question: As is, you can relate one extract to another multiple times so long as the relation is different. Thus one person can say X contrasts Y while another can say X confirms Y. This can be confusing, but such conflicts do come up. 

As is, you can also say both yourself, which I think is an error but haven't fixed yet. 

Regarding feedback, how about I simply remove any extracts that have already been marked related from the search results? That would be an easy fix. They'd reappear in the search results if you remove the relation in case you change your mind (again).

**Comment by hlesaint** [comment]
Good question, and difficult. When I see that I can relate extracts both in contrast and confirmed by, it may feel a bit like a bug. But if I want to relate the extract confirmed by, but I can't, because someone else already put it in contrast to, falsely (!!!), then I feel restricted in my intention to make things right. I'd consider this feeling more negative. 

I think both should be possible, as both is theoretically possible. 

Another question is, when I think that e.g., "confirmed by" is simply not true, can I remove it? In this case all relations of an extract would be displayed in the modify page with possibility to cross them out.

**Comment by tgetgood** [comment]
I don't think anyone should be able to simply remove something someone else added. That will engender endless strife. 

But you should be able to show your dissent with a decision. Should this be by down voting the relation? Flagging it in some way "factually inaccurate", "conflict of interest", "beating a dead horse", "anecdotal", &c.?  Suggesting an edit (such as removal) which would have to be approved by the author, or a moderator before going into effect?

Maybe the best thing to do would simply be to leave relations be. There will eventually be many, many relations on a given extract (if we're being ambitious), and many of those will contradict each other. But no one will be able to view the raw set of relations by themselves, they'll need some sort of graphical or statistical summary, and in those, small deviations like a single dissenting voice will be drowned in the rest of the data. 

We can also try to emphasise the outliers, but that's a different conversation.

**Comment by hlesaint** [comment]
Fair point. I fully agree to leave relations be. If we colorize the connections in the network view (neural=blue, +=green, -=red), then an extract in contrast to and confirmed by another extract would share a red and a green connection with the related extract. That's fine.

Yet, I also like the idea of suggesting an edit (such as removal) to the original relating author to approve, which might be a good way to think this through foster, discussion and further clarity. This could be something for a later stage.
