### ISSUE TITLE
new tags and tag order

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#53]
To allow for good tagging I divided "modality" into "modality" & "scale" and included the tag "awake" for data sets, which include awake references (makes sense for proper comparison). 

I changed the order of tags, grouped them together based on category, and included some new subtags.

I think the current design helps to keep better overview: 

![tags png 001](https://user-images.githubusercontent.com/44240982/82754822-e1c81a00-9dcf-11ea-8a84-9da350c07165.png)

[tags.pdf](https://github.com/openmindanesth/openmind/files/4673556/tags.pdf)

**Comment by hlesaint** [comment]
I'll think about nice recognizable symbols that represent the tag categories. If we show the written tag by mouse over, it would allow a better overview at a glimpse and again speed up the process.

**Comment by tgetgood** [comment]
I'd warn against being too aggressive with icons. Icons aren't nearly as universal as is generally believed, and a good concise phrase will almost always be more clear.

There's a lot of debate about whether icons really bring more benefits than the confusion they cause within the HCI community. Jef Raskin (the lead designer of the original macintosh ui) hated icons. His advice was to just use a word instead unless it's impossible. 

I don't think we have to be so dogmatic, but designing a set of good, intuitive icons will involve a lot of trial and error.

**Comment by hlesaint** [comment]
You're probably right. I got carried away by the idea of visual clues for a second. :)

**Comment by hlesaint** [comment]
This has translated well into the new tags. 

Here it would be great if we could use the order /sequence proposed in the illustration above. 

For the highest level I tried to group the tags into 3 themes: 
species, drug-related, and experiment-related:
species -- awake-anesthetic-level-physiology -- modality-scale-application
Maybe we could introduce a bit more spacing between different themes (indicated by -- ) or less spacing within the same themes (indicated by-).

The lower levels are sequenced/ordered by other themes, e.g., decreasing complexity from primate to rodent: human - monkey - rat - mouse
At these levels the order is also thought through, but no further groupings were intended.
