### ISSUE TITLE
modify extract page: edit

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#55]
If "edit" is clicked you come to the "modify extract" page. It would be great, if all informations from the the actual version of the extract would be already in there, so you need to actively change it. Otherwise, there is a high chance to loose info unintentionally.

**Comment by tgetgood** [comment]
Pending testing, this is complete.

**Comment by hlesaint** [comment]
All info is displayed on the modify extract page. 

Yet, when I enter new info, save and I leave the modify extract page it is not displayed in the extract search site. When I click the edit link again the info is still on the modify extract page.

On another note, would it make sense to go back to the extract search site once you click save? This would be a strong feedback and you usually press save when you're done, particularly as extract creation and modification is a quick process.

**Comment by tgetgood** [comment]
It does go back to the search page once the edit has been saved on the server. Unfortunately this can take a few seconds sometimes. 

I don't see any modified extracts on the productions site, so this might well be broken.

**Comment by tgetgood** [comment]
After much ado, editing is fully functional without the ui delay. It can still take a second or two to save the changes but the client goes on in the meantime.
