### ISSUE TITLE
Recent version with browser refreshing 

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#60]
Unfortunately I do not get the latest version when I refresh my browser (Brave). Also the deletion of cookies does not work. I have now used Firefox to visit the site for the first time to get the latest version. Temporarily I would be interested in what I have to do to stay up to date. In the long run, it would be great if OM would be up to date with refreshing of the browser. Since many people will have similar problems, they might miss the updates, which would be a pity.

**Comment by tgetgood** [comment]
Your browser should only be caching the page for a day or two. Try again in Brave tomorrow and let me know if it's updated. We don't want to disable caching because it makes the site a lot faster, but I agree, we don't want anyone missing updates.

**Comment by hlesaint** [comment]
All good. Brave is updated and displays the current version.

**Comment by tgetgood** [comment]
Glad to hear it. I'll close this then.
