### ISSUE TITLE
pubmed link, or doi, or pmc

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#66]
Entering the pubmed link is already straight-forward. Even more so can be the doi, which is always printed on the article itself. Searching for the doi in pubmed also suffice to unambiguously identify the article. 

Sometimes when searching for a pubmed link one gets the pmc version (PubMed Central, which is a free full-text archive), which looks like that:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4731789/

It would be great if OM would recognize pmc versions and ideally redirect to the original pubmed article.

**Comment by tgetgood** [comment]
Are you aware of any database that we could use to lookup by DOI? doi.org redirects to the publisher of the article, but it's not feasible to directly interact with every journal out there. Certainly not in the short term.

I'll look into using pubmed search for doi resolution. PMC shouldn't be overly difficult to integrate.

**Comment by hlesaint** [comment]
Indeed every article on pubmed is peer-reviewed. Let's go with your idea you wrote in the email: automatically detect peer-reviewed vs preprint by looking at the link (pubmed vs biorxiv), plus switch to override the automatic choice.

I'd propose something along the lines:

– enter url (pubmed, biorxiv) > extracts info from homepage (only from pubmed or biorxiv)
– enter url (pmc) > redirects to pubmed > extracts info from homepage (pubmed)
– enter doi (e.g., 10.1101/2020.05.19.101196) or doi-url (e.g., https://doi.org/10.1101/2020.05.19.101196) > extracts doi > searches for doi in pubmed > not found? > looks in biorxiv > not found? > echos: article not found, please input manually > input windows appear

I just tested the search with doi for pubmed and biorxiv:

Pubmed: If the article is pubmed listed the article page opens directly. If not, a page opens showing a list of multiple potential articles. Seems unambiguous to me.

Biorxiv: If the article is biorxiv listed a page opens showing a list of 1 potential article (which is likely the right one, you have to click on it to get to the article page). If not, a page opens showing no articles.

**Comment by hlesaint** [comment]
Even better for the biorxiv option: doi (e.g., 10.1101/2020.05.19.101196) > automatically completed to doi-url (e.g., https://doi.org/10.1101/2020.05.19.101196) > redirected to biorxiv? > then we're already at the articles page.

**Comment by hlesaint** [comment]
This would start with searching in pubmed with doi > if nothing found, searching in browser for doi-url > if redirected to biorxiv > we are on article page > if not > manual input

**Comment by tgetgood** [comment]
All of the below formats are now recognised by the source article search: 

https://pubmed.ncbi.nlm.nih.gov/22945293/
https://doi.org/10.1002/nbm.1613
10.1002/nbm.1613
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6075724/

bioarxiv urls are not yet working.
