### ISSUE TITLE
click instead of mouse over

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#67]
Yes, mouse over was a great idea, which immediately gives you all information you hover above. But you get really all information on your way from left to right when you're just interested in a particular thing. This can get quite annoying, especially the more features an extract has and the more extracts there are. Also sometimes the windows do not close properly.

I assume it would be better to go by one click to open. Click a second time (or somewhere else) to close. What do you think? 

At a later stage we can think about double click for open in new page. But this has time.

**Comment by tgetgood** [comment]
This is reasonable. I've been able to slow the page to a halt by opening thousands of hover windows recursively. 

How about click to open, but closes automatically when the mouse leaves the popup? That way clicking on the open window could bring you somewhere else. This is especially important in the related material where you can open windows inside windows inside...

**Comment by hlesaint** [comment]
Good point. That fastens the process and feels more dynamic.

**Comment by hlesaint** [comment]
And maybe we have one exception: the figure. Mouse over the thumbnail to extend the figure fastens the process and is not too messy when navigating the cursor through the page. 

I believe one wants to have that immediately while the other options are rather "additional information".

**Comment by hlesaint** [comment]
I'd also suggest one further exception: the meta-info symbol. Mouse over expands the meta-info including the total votes. 

How about expanding by mouse over and voting by clicking the symbol, either on the extract or on the meta-info field that expands. Once you clicked the symbol there could be an outer ring (or line) around the symbol in a darker color to show that you voted the extract. #41

**Comment by tgetgood** [comment]
When you have a line of symbols and clicking on them does different things is can be confusing. Generally you want the same action taken by someone to produce an homologous result wherever it might be. 

If hovering over the meta-info shows a vote icon, then a hover->click isn't too much work. 

If we want voting go be a very fast operation, then we can just add vote buttons to the feature bar, or below the figure.

**Comment by hlesaint** [comment]
Agreed.
