### ISSUE TITLE
Authors' names extraction

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#69]
Two issues with the author's names:

1. The initials of the first and second name are additionally displayed (on extract and detailed abstract view), e.g.: 
Fatima A Nasrallah > Fatima A FA Nasrallah

2. Authors' first names + initials are displayed on the extract, e.g.: 
Fatima A FA Nasrallah, et al. (2014)

Better options might be:
Nasrallah et al. (2014) > only last name, without comma, or 
Nasrallah, FA et al. (2014) > last name, comma, initials

**Comment by tgetgood** [comment]
Pubmed recently changed their format from "last, initial" to "first initials last". I like the change in general, but you're right; it's no good with et al. 

This shall be fixed.
