### ISSUE TITLE
Hide detailed source article entry 

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#74]
The detailed source article entry is an important feature. However, it makes the appearance of the create /edit extract page for published articles rather complex. As the detailed source article entry is used rarely for published articles, we could hide it behind an "article details" button below the "find paper" search bar that expand on click and also when the automated link detection fails to find an article.

Only in case of published articles of course, for lab reports detailed entry is default. 

What do you think?

**Comment by tgetgood** [comment]
I've put the old source article preview back so that you have something to check to make sure the system found the right article. I think it's reasonably compact, but I could also add an option to collapse it as well and just show the title of the article (or the citation might be better).

**Comment by hlesaint** [comment]
Collapse and citation would be perfect. I certainly agree it's reasonably compact. Yet, as a contributor, I'd find it convenient to trust the extraction and not to pay attention to the details, but still have access to them and change them if I find that they are not correct. I therefore like the idea of showing the citation, which provides a strong clue whether the right article was found. This point is not top priority, but I think it simplifies.
