### ISSUE TITLE
Extract search site: blueish color design

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#9]
color design (a bit early but these are salient details to me): maybe we stick to blueish shades. black outlines with gray /green fillings look a bit odd.

**Comment by hlesaint** [comment]
I personally don't like green, but I think the black outline + text is most problematic, since it appears very different in style.

**Comment by hlesaint** [comment]
![E5D08CEB-6501-4D50-91D7-7A2117CDD732](https://user-images.githubusercontent.com/44240982/63125818-e2b15d00-bfae-11e9-9d76-a10f57f0d0b3.png)

**Comment by hlesaint** [comment]
it might be an idea to highlight selections by lighter colors. so we stay with a simple yet contemporary style: no outlines, no salient contrasts.

**Comment by tgetgood** [comment]
I agree that the colour scheme was not given sufficient thought and needs an overhaul. Thanks for the proposal, I think it's a big step up. 

I think we need a little more contrast --- I find it difficult to read the button labeled "deep" without leaning in --- but otherwise, let's go with this.

**Comment by hlesaint** [comment]
Great! Looking forward to!

**Comment by tgetgood** [comment]
There's a new design up at http://openmind-eu.herokuapp.com/.

@hlesaint comments?

**Comment by hlesaint** [comment]
Great!

**Comment by tgetgood** [comment]
Glad you like it. I'll consider this done for now then.
