### ISSUE TITLE
deleting empty "repos" from extract

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#90]
"repos" should only appear on the extract if there is actually a repository linked to it.

**Comment by tgetgood** [comment]
That's reasonable. Should the same also apply to "related" and "tags"?

**Comment by hlesaint** [comment]
Yes, I think this would help to identify extracts that are incomplete or need some embedding.

**Comment by hlesaint** [comment]
Thanks for the fix. One brief consideration: I see the point for keeping the features' respective positioning on the extract. However, being not familiar with the concept it looks somewhat "untidy", as they were just randomly distributed or like a lack of proper positioning. 

What do you think about keeping them on the extract, but making them very light grey instead?
