### ISSUE TITLE
more than 1 PI for lab notes

### ISSUE THREAD

**Issue by hlesaint** [openmindanesth/openmind#92]
It would be great if one could state more persons involved in a finding for a lab note than the principle investigator. I think it's a good idea to have the possibility for multiple PI(s), but also researchers or co-workers to state, maybe with a [+] .

**Comment by tgetgood** [comment]
Giving credit to more than one person is certainly what we want to do. What would the best terminology be? 

Rather than single out a principle investigator, we could just have a list of "principles", just "investigators", "observers", or maybe "authors" again. Is there a preferred terminology?

**Comment by hlesaint** [comment]
I like "investigators". 

The first 2 are on the extract (e.g., Getgood, T, and Reimann, HM, 2020), with >2 it gets Getgood, T et al., 2020. 

The others are listed in the extract detailed view, and they should get also appear when clicking on "investigator et al., 2020" on the extract. 

It would be good to have that window for a sort of abstract, like in articles, where you have some space to briefly describe the experiment and hack in some details that are neither part of the figure nor the finding. (Maybe you can give a title, optionally.)
